name: gymfit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  swipeable_page_route: ^0.4.2
  uuid: ^4.4.0
  shared_preferences: ^2.0.6
  gif_view: ^1.0.0
  circular_countdown_timer: ^0.2.4
  just_audio: ^0.9.40
  google_nav_bar: ^5.0.6
  emailjs: ^4.0.0
  intl: ^0.20.0
  mongo_dart: ^0.10.4
  bcrypt: ^1.1.3
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  fluttertoast: ^8.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "/Users/ferdinandodelvecchio/apps/ProgettoPalestra/gymfit/assets/EwoLogo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/GymFitLOGO-2.png
    - assets/GymFitLOGO-2-2.jpg
    - assets/sounds/timer.ogg